config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  # get '/users', to: 'pages#home'

  # Pages
  root to: 'pages#home'
  get '/offline', to: 'pages#offline', as: :offline
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/change-language', to: 'pages#language', as: :language

  # Webhook
  namespace :webhooks do
    scope :postmark do
      post 'delivery-email', to: 'postmark_emails#delivery'
    end
  end

  # Errors
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Models
  resources :houses do
    collection do
      get :search
      get :export_data
      get :pdf_generator
    end
  end

  # API Endpoints
  namespace :api do
    namespace :v1 do
      resources :houses
    end
  end

  # Develomment tools
  authenticate :user, ->(user) { user.role.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
    mount LetterOpenerWeb::Engine, at: "/letter_opener", as: :letter_opener if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks", as: :maintenance_tasks
  end
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs', as: :swagger_api
end

app/controllers/api/v1/houses_controller.rb
class Api::V1::HousesController < Api::V1::ApiController
  before_action :load_house, only: %i[show update destroy]
  before_action :build_house, only: %i[create update]

  def index
    @houses = House.all
  end

  def show; end

  def create
    save_house(:created)
  end

  def update
    save_house(:ok)
  end

  def destroy
    @house.destroy
  end

  private

  def load_house
    @house ||= House.find(params[:id])
  end

  def build_house
    @house ||= House.new
    @house.attributes = house_params
  end

  def house_params
    house_params = params
    house_params ? house_params.permit(:name, :address, :user_id) : {}
  end

  def save_house(status)
    if @house.save
      render :show, status: status
    else
      render json: { errors: @house.errors }, status: :unprocessable_entity
    end
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy]

  def index
    @houses = policy_scope(House)
  end

  def search
    authorize :house, :search?
    index
    @houses = @houses.search_by_name_and_address(params[:query]).uniq if params[:query].present?
    render :index
  end

  def show; end

  def new
    @house = authorize House.new
    @title = t('house.modal.new')

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def create
    @house = authorize House.new(house_params)
    @house.user = current_user

    respond_to do |format|
      if @house.save
        @notice = t('house.create.success')
        format.html { redirect_to houses_path, notice: @notice }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
      format.js {}
    end
  end

  def edit
    @title = t('house.modal.edit')

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def update
    respond_to do |format|
      if @house.update(house_params)
        @notice = t('house.update.success')
        format.html { redirect_to house_path(@house), notice: @notice }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
      format.js {}
    end
  end

  def destroy
    @house.destroy
    @notice = t('house.delete.success')

    respond_to do |format|
      format.html { redirect_to houses_path, notice: @notice }
      format.js {}
    end
  end

  def export_data
    authorize :house, :export_data?
    attributes = %w[name address latitude longitude created_at updated_at user_id user_full_name]

    ExportToEmailJob.perform_later(attributes: attributes, element_class: "House", user_id: current_user.id)
    redirect_to root_path, notice: t('house.csv_export.success')
  end

  def pdf_generator
    authorize :house, :pdf_generator?
    @houses = House.includes([:user]).all

    respond_to do |format|
      format.pdf { render pdf: "houses_#{DateTime.now.strftime('%d-%m-%Y_%Hh%M')}", layout: "pdf.html.erb" }
    end
  end

  private

  def set_house
    @house = authorize policy_scope(House).find(params[:id])
  end

  def house_params
    params.require(:house).permit(:name, :address, :description, photos: [])
  end
end

app/views/houses/_form.html.erb
<div class="container my-5">
  <h1><%= title %></h1>
  <%= simple_form_for(house, remote: remote) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  label: t('house.form.name'),
                  input_html: { autocomplete: "name" } %>
      <%= f.input :address,
                  required: true,
                  label: t('house.form.address'),
                  input_html: { autocomplete: "address", data: { address_autocomplete_target: "address" }, class: "d-none" },
                  wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] }} %>
      <%= f.input :description,
                  as: :rich_text_area,
                  label: t('house.form.description'),
                  input_html: { autocomplete: "description" } %>
      <%= f.input :photos,
                  as: :file,
                  label: t('house.form.photos'),
                  input_html: { multiple: true } %>
    </div>

    <div class="form-errors text-danger">
      <ul class="d-none helpBlock"></ul>
    </div>

    <div class="form-actions">
      <%= f.button :submit, t('modal.save'), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/houses/_index.html.erb
<div class="container my-5 w-100" id="<%= dom_id(user, 'houseIndex') %>">
  <h1><%= t('house.index.title') %></h1>
  <p class="mb-5"><%= link_to t('house.new'), new_house_path, remote: true, class: "btn btn-primary", data: { "bs-toggle" => "modal", "bs-target" => "#staticBackdrop" } %></p>

  <%= form_with url: search_houses_path, method: :get do %>
    <div class="d-flex">
      <%= text_field_tag :query,
          params[:query],
          class: "form-control w-25",
          placeholder: t('house.index.search') %>
      <%= button_tag type: "submit", class: "btn btn-primary" do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>
  <% end %>

  <%= link_to houses_path, class: "btn btn-primary", title: t('house.index.reset_search') do %>
    <i class="fas fa-redo-alt"></i>
  <% end %>

  <div class="row mb-5 mt-2">
    <% houses.each do |house| %>
      <%= render(HouseCardComponent.new(house: house)) %>
    <% end %>
  </div>
</div>

app/views/houses/create.js.erb
<%= render "shared/modal_ajax", object: @house, notice: @notice, alert: @alert %>

app/views/houses/destroy.js.erb
<%= render "shared/flashes_ajax", notice: @notice, alert: @alert %>

app/views/houses/edit.html.erb
<%= render "form", title: @title, house: @house, remote: false %>

app/views/houses/edit.js.erb
$('#modal-body').html("<%= j render 'houses/form', title: @title, house: @house, remote: true %>");

app/views/houses/index.html.erb
<%= render 'index', houses: @houses, user: current_user %>

app/views/houses/new.html.erb
<%= render "form", title: @title, house: @house, remote: false %>

app/views/houses/new.js.erb
$('#modal-body').html("<%= j render 'houses/form', title: @title, house: @house, remote: true %>");

app/views/houses/pdf_generator.pdf.erb
<div class="container my-5">
  <h2 class="text-left"><%= t('house.list') %></h2>

  <table class="table table-hover table-responsive text-center">
    <thead class="thead-light">
      <tr>
        <th scope="col"><%= t('house.form.name') %></th>
        <th scope="col"><%= t('house.form.address') %></th>
        <th scope="col"><%= t('house.form.user') %></th>
      </tr>
    </thead>
    <tbody>
      <% @houses.each do |house| %>
        <tr>
          <td><%= house.name %></td>
          <td><%= house.address %></td>
          <td><%= house.user_full_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/houses/show.html.erb
<div class="container my-5">
  <p class="pop-title"><%= @house.name %></p>
  <p class="pop-time"><%= t('house.created_at') %> <%= @house.created_at.strftime("%d-%m-%Y") %></p>
  <p class="pop-user"><%= @house.address %></p>
  <p><%= @house.description.blank? ? "<em>#{t('house.no_description')}</em>".html_safe : @house.description %></p>
  <br>
  <% if @house.photos.attached? %>
    <% @house.photos.each do |photo| %>
      <%= link_to rails_blob_path(photo), target: "_blank" do %>
        <%= image_tag photo, height: 50, width: 50, class: "m-1" %>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <div><%= link_to t('back'), :back %></div>
</div>

app/views/houses/update.js.erb
<%= render "shared/modal_ajax", object: @house, notice: @notice, alert: @alert %>