config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  # get '/users', to: 'pages#home'

  # Pages
  root to: 'pages#home'
  get '/offline', to: 'pages#offline', as: :offline
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/change-language', to: 'pages#language', as: :language

  # Webhook
  namespace :webhooks do
    scope :postmark do
      post 'delivery-email', to: 'postmark_emails#delivery'
    end
  end

  # Errors
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Models
  resources :houses do
    collection do
      get :search
      get :export_data
      get :pdf_generator
    end
  end

  # API Endpoints
  namespace :api do
    namespace :v1 do
      resources :houses
    end
  end

  # Develomment tools
  authenticate :user, ->(user) { user.role.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
    mount LetterOpenerWeb::Engine, at: "/letter_opener", as: :letter_opener if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks", as: :maintenance_tasks
  end
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs', as: :swagger_api
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_flashes_ajax.js.erb
<%# flash notice or alert %>
<% if notice %>
  $(".btn-close").click();
  $("#flashes").append("<%= j render 'shared/flashes', notice: notice %>");
<% elsif alert %>
  $(".btn-close").click();
  $("#flashes").append("<%= j render 'shared/flashes', alert: alert %>");
<% end %>

app/views/shared/_info_window.html.erb
<div class="container">
  <div>
    <p class="pop-title"><%= house.name %></p>
    <p class="pop-time"><%= t('house.created_at') %> <%= house.created_at.strftime("%d-%m-%Y") %></p>
    <p class="pop-user"><%= house.address %></p>
    <%= link_to path do %>
      <i class="fas fa-eye"></i>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t('modal.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_ajax.js.erb
<%# create or update ajax %>
<% if object.errors.any? %>

  $(".helpBlock").removeClass("d-none");
  $(".error-message").remove();
  <% object.errors.full_messages.each do |message| %>
    $(".helpBlock").append('<li class="error-message"><%= escape_javascript(message)%></li>');
  <% end %>

<% else %>

  $(".helpBlock").addClass("d-none");

<% end %>

<%= render "shared/flashes_ajax", notice: notice, alert: alert %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-2">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'apple-icon.png' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Afficher le menu de navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="dropdown-toggle text-decoration-none nav-link" role="button" id="languageDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('languages.title') %>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="languageDropdown">
          <%= link_to t('languages.french'), language_path(locale: "fr"), class: "dropdown-item #{'font-weight-bold' if session[:locale] == 'fr'}" %>
          <hr class="dropdown-divider">
          <%= link_to t('languages.english'), language_path(locale: "en"), class: "dropdown-item #{'font-weight-bold' if session[:locale] == 'en'}" %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t('user.index'), root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="dropdown-toggle text-decoration-none" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.avatar.attached? ? current_user.avatar : "empty-avatar.png", class: "avatar-large" %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to t('user.my_profile'), profil_path(current_user.slug), class: "dropdown-item" %>
            <%= link_to t('house.my_houses'), houses_path, class: "dropdown-item" %>
            <%= link_to t('devise.registrations.edit_account'), edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to t('devise.sessions.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <hr class="dropdown-divider">
            <% if current_user.role.admin? %>
              <%= link_to "Sidekiq", sidekiq_path, class: "dropdown-item", target: "_blank" %>
              <%= link_to "Maintenance Tasks", maintenance_tasks_path, class: "dropdown-item", target: "_blank" %>
              <%= link_to "Letter Opener", letter_opener_path, class: "dropdown-item", target: "_blank" %>
            <% end %>
            <%= link_to "API Swagger", swagger_api_path, class: "dropdown-item", target: "_blank" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('devise.sessions.signin'), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pwa_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="192x192" href="<%= image_path 'icons/android-icon-192x192.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_path 'icons/ms-icon-144x144.png' %>">
<meta name="theme-color" content="#ffffff">