config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  # get '/users', to: 'pages#home'

  # Pages
  root to: 'pages#home'
  get '/offline', to: 'pages#offline', as: :offline
  get '/profil/:slug', to: 'pages#profil', as: :profil
  get '/change-language', to: 'pages#language', as: :language

  # Webhook
  namespace :webhooks do
    scope :postmark do
      post 'delivery-email', to: 'postmark_emails#delivery'
    end
  end

  # Errors
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Models
  resources :houses do
    collection do
      get :search
      get :export_data
      get :pdf_generator
    end
  end

  # API Endpoints
  namespace :api do
    namespace :v1 do
      resources :houses
    end
  end

  # Develomment tools
  authenticate :user, ->(user) { user.role.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
    mount LetterOpenerWeb::Engine, at: "/letter_opener", as: :letter_opener if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks", as: :maintenance_tasks
  end
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs', as: :swagger_api
end

app/views/pages/home.html.erb
<% canonical(root_url) %>

<div class="container mb-5">
  <%= render(UserCardsComponent.new(title: "Admins", users: @admins)) %>
  <%= render(UserCardsComponent.new(title: t('user.customers'), users: @customers)) %>

  <% if current_user.present? && current_user.role.admin? %>
    <h2 class="mt-5"><%= t('user.admin_actions') %></h2>

    <%= link_to export_data_houses_path, class: "btn btn-primary" do %>
      <i class="fas fa-download"></i> <%= t('user.admin.csv_export') %>
    <% end %>

    <%= link_to pdf_generator_houses_path(format: :pdf), target: "_blank", rel: "noopener noreferer", class: "btn btn-primary" do %>
      <i class="fas fa-download"></i> <%= t('user.admin.pdf_export') %>
    <% end %>
  <% end %>
</div>

app/views/pages/offline.html.erb
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
      body {
        background-color: #00a4cd;
        color: #ffffff;
        padding: 4rem 2rem;
      }
      .text-center {
        text-align: center;
      }
      .container {
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div class="container text-center">
      <img src="/apple-icon.png" alt="logo">
      <h1>Vous avez besoin d'une connexion Internet fonctionnelle pour utiliser ce site Web</h1>
      <p>Le mode hors ligne n'est pas encore pris en charge</p>
    </div>
    <script>
      window.addEventListener('online', () => {
        window.location.reload();
      });
    </script>
  </body>
</html>

app/views/pages/profil.html.erb
<div class="container text-center">
  <h1 class="my-5"><%= t('user.profile.title', slug: @user.pseudo) %></h1>
  <%= image_tag @user.avatar, class: "avatar" %>
  <span class=<%= "text-green" if @user.online %>><%= @user.full_name %></span>

  <div class="my-5">
    <h2><%= t('user.profile.houses') %></h2>
    <% if current_user.present? && current_user == @user %>
      <%= link_to t('user.profile.manage_houses'), houses_path, class: "btn btn-primary" %>
    <% end %>
  </div>
  <% if @houses_geocoded.empty? %>
    <em><%= t('user.profile.empty_houses') %></em>
  <% else %>
    <div style="width: 100%; height: 600px;"
        class="mb-5"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-locale-value="<%= I18n.locale %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <% end %>
</div>